const STORAGE_KEYS = {
  // APP_CONTEXT_KEY
  LANGUAGE_KEY: "LANGUAGE",
  COLOR_SCHEME_KEY: "colorScheme",

  // USER_CONTEXT_KEY
  USER_INFO_KEY: "USER_INFO",
  ACCESS_TOKEN_KEY: "ACCESS_TOKEN",
  REFRESH_TOKEN_KEY: "REFRESH_TOKEN",

  ONBOARDING_KEY: "has_seen_onboarding",
} as const;

export default STORAGE_KEYS;
